### ISSUE TITLE
ime repozitorijuma

### ISSUE THREAD

**Issue by vhristodulo** [ictcollege/CloudICT#1]
trebalo bi da vratimo ime repozitorijuma u ictcloud, kao i ime application foldera u ictcloud
to ce imati posledice na vasa lokalna git podesavanja
odgovorite svi da li se slazete sa tim, pa da menjamo

**Comment by matic31** [comment]
moze, ako ce to samo da renamuje ceo projekat i ako to prodje onda da, mada
ne znam zasto je to bitno
zbog podudaranja imena baze projekta, cega vec?

**Comment by vhristodulo** [comment]
da, mozda to nije bitno,
ali zamisli recimo da se metoda za mysql u php-u zove sqlmy_connect() ili da se folder za javascript zove sj (scriptjava) i tome slicno 
doslo bi do konfizije jer se ne prati konzistentnost imena projekta tamo gde se ono upotrebljava
Kojic je projekat inicijalno krstio kao ict cloud (tako se zove i maling lista) i mislim da bi trebalo da postujemo konzistentnost tog imena kroz ceo projekat 
ako cemo da preimenujemo projekat u cloudict - ok - ali onda da tako odlucimo i da kazemo od sada se on tako zove, pa da ispratimo to ime u celom projektu

**Comment by matic31** [comment]
Vazi, slazem se, samo da se dogovorimo sa ostalima, btw ne znam ko sve i
vidi ovo s obzirom da je poslato na ictcollege/CloudICT.
Dogovaramo se u ponedeljak.

2015-06-06 22:11 GMT+02:00 Vladislav Hristodulo notifications@github.com:

**Comment by vhristodulo** [comment]
ok.
ovo vide svi u organizaciji (i sire jer su cela organizacija i repozitorijumi public)
tako da necu zatvarati ovaj issue, jer mozda jos neko bude komentarisao.

**Comment by develm** [comment]
Kad sam pravio projekat ime ictcloud nije bilo dostupno.Ime porjekta može da se izmenu u opcijama, vaš lokalni repo će idalje raditi međutim link bi trebalo da se promeni na novi, postoje dva načina:
1. možeš da izbrišeš lokalni repo i da ga klonujes u novom folderu sa novim linkom (obavezno uradi push da ne bi izgubio podatke)
2. postoji komanda koja menja url:
   git remote set-url origin new_url
